use bds;
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bến Nghé',1);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bến Thành',1);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cầu Kho',1);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cầu Ông Lãnh',1);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cô Giang',1);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nguyễn Cư Trinh',1);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nguyễn Thái Bình',1);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phạm Ngũ Lão',1);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Định',1);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đa Kao',1);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Khánh',2);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Lợi Đông',2);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Phú',2);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình An',2);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình Khánh',2);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình Trưng Tây',2);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình Trưng Đông',2);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cát Lái',2);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Mỹ Lợi',2);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thảo Điền',2);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thủ Thiêm',2);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('P.1',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('P.2',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('3',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('4',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('5',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('6',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('7',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('8',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('9',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('10',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('11',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('12',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('13',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('14',3);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('1',4);

INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('2',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('3',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('4',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('5',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('6',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('7',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('8',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('9',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('10',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('11',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('12',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('13',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('14',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('15',4);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('18',4);

INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('1',5);

INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('2',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('3',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('4',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('5',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('6',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('7',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('8',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('9',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('10',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('11',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('12',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('13',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('14',5);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('15',5);

INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('1',6);

INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('2',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('3',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('4',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('5',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('6',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('7',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('8',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('9',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('10',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('11',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('12',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('13',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('14',6);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình Thuận',7);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Mỹ',7);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Thuận',7);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Hưng',7);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Kiểng',7);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Phong',7);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Phú',7);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Quy',7);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Thuận Tây',7);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Thuận Đông',7);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('1',8);

INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('2',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('3',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('4',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('5',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('6',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('7',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('8',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('9',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('10',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('11',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('12',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('13',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('14',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('15',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('16',8);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hiệp Phú',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Bình',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Phước',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Thạnh Mỹ',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Trường',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Hữu',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phước Bình',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phước Long A',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phước Long B',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Phú',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tăng Nhơn Phú A',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tăng Nhơn Phú B',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trường Thạnh',9);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('1',10);

INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('2',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('3',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('4',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('5',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('6',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('7',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('8',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('9',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('10',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('11',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('12',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('13',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('14',10);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('15',10);

INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('1',11);

INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('2',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('3',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('4',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('5',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('6',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('7',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('8',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('9',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('10',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('11',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('12',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('13',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('14',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('15',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('16',11);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Phú Đông',12);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hiệp Thành',12);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Chánh Hiệp',12);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Hưng Thuận',12);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Thới Hiệp',12);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Thới Nhất',12);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Lộc',12);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Xuân',12);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thới An',12);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Mỹ Tây',12);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Hưng Thuận',12);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nam Cát Tiên',23);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Núi Tượng',23);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Lâm',23);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Lập',23);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Lộc',23);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Thịnh',23);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Trung',23);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Điền',23);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tà Lài',23);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Sơn',23);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trà Cổ',23);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đắc Lua',23);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cống Vị',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Giảng Võ',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim Mã',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Liễu Giai',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngọc Hà',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngọc Khánh',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nguyễn Trung Trực',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phúc Xá',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quán Thánh',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thành Công',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trúc Bạch',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Phúc',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Điện Biên',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đội Cấn',25);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ba Trại',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ba Vì',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cẩm Lĩnh',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cam Thượng',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Châu Sơn',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Chu Minh',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cổ Đô',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Khánh Thượng',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Minh Châu',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Minh Quang',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phong Vân',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Châu',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Cường',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Phương',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Sơn',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Đông',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Đà',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tản Hồng',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tản Lĩnh',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tây Đằng',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thái Hòa',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thuần Mỹ',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thụy An',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tiền Phong',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tòng Bạt',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vân Hòa',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vạn Thắng',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vật Lại',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yên Bài',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Quang',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Thái',26);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Dịch Vọng',27);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Dịch Vọng Hậu',27);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mai Dịch',27);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nghĩa Tân',27);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nghĩa Đô',27);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quan Hoa',27);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Hòa',27);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yên Hòa',27);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Chúc Sơn',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Chính',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hoàng Diệu',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hoàng Văn Thụ',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hồng Phong',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hợp Đồng',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hữu Văn',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lam Điền',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mỹ Lương',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nam Phương Tiến',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngọc Hòa',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngọc Sơn',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Nam An',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Nghĩa',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phụng Châu',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quảng Bị',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Tiến',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Bình',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thượng Vực',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thụy Hương',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thủy Xuân Tiên',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tiên Phương',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tốt Động',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trần Phú',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Hòa',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trường Yên',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Văn Võ',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Mai',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đại Yên',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Lạc',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Phú',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Phương Yên',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Sơn',28);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hạ Mỗ',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hồng Hà',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Liên Hà',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Liên Hồng',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Liên Trung',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phùng',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phương Đình',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Song Phượng',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Hội',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Lập',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thọ An',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thọ Xuân',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thượng Mỗ',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Châu',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đan Phượng',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Tháp',29);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bắc Hồng',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cổ Loa',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Dục Tú',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hải Bối',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim Chung',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim Nỗ',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Liên Hà',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mai Lâm',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nam Hồng',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nguyên Khê',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tàm Xá',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thị trấn Đông Anh',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thụy Lâm',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tiên Dương',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Uy Nỗ',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vân Hà',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vân Nội',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Việt Hùng',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Ngọc',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Võng La',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Canh',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Nộn',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đại Mạch',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Hội',30);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cát Linh',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hàng Bột',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Khâm Thiên',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Khương Thượng',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim Liên',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Láng Hạ',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Láng Thượng',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nam Đồng',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngã Tư Sở',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nguyễn Trãi',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ô Chợ Dừa',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phương Liên',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phương Mai',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quang Trung',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quốc Tử Giám',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thịnh Quang',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thổ Quan',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Liệt',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Phụng',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Tự',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Văn Chương',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Văn Miếu',31);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Chiến Thắng',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cự Khối',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Dương Hà',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Gia Lâm',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Giang Biên',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hồng Tiến',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim Lan',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Biên',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngọc Thụy',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ninh Hiệp',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phù Đổng',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phúc Lợi',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quang Minh',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quang Trung I',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quang Trung II',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quyết Chiến',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quyết Thắng',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quyết Tiến',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Hưng',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạch Bàn',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thừa Thiên',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thượng Thanh',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tiến Bộ',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tiền Phong',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Toàn Thắng',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Hưng',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Thành',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vân Dục',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Việt Hưng',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yên Viên',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đại Hưng',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đặng Xá',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đình Xuyên',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đức Thắng',32);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Biên Giang',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Dương Nội',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hà Cầu',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kiến Hưng',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('La Khê',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mỗ Lao',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nguyễn Trãi',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú La',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Lãm',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Lương',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phúc La',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Văn Khê',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vạn Phúc',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Văn Quán',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yên Nghĩa',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yết Kiêu',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Mai',33);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bách Khoa',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bạch Mai',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bạch Đằng',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bùi Thị Xuân',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cầu Dền',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cửa Nam',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lê Đại Hành',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Minh Khai',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngô Thì Nhậm',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nguyễn Du',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phạm Đình Hổ',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phố Huế',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quỳnh Mai',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Lương',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Nhàn',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trương Định',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Tuy',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Mác',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Nhân',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Tâm',34);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Khánh',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Thượng',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cát Quế',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Di Trạch',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Dương Liễu',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim Chung',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('La Phù',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lại Yên',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Minh Khai',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Đồng',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Song Phương',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tiền Yên',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trạm Trôi ',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vân Canh',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vân Côn',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yên Sở',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đắc Sở',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông La',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đức Giang',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đức Giang',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đức Thượng',35);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Chương Dương',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cống Vị',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cửa Nam',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cửa Đông',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hàng Bạc',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hàng Bài',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hàng Bồ',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hàng Bông',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hàng Buồm',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hàng Gai',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hàng Mã',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hàng Trống',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hàng Đào',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lý Thái Tổ',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phan Chu Trinh',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phúc Tân',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trần Hưng Đạo',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tràng Tiền',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Xuân',36);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bồ Đề',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cự Khối',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Gia Thụy',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Giáp Bát',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hoàng Liệt',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hoàng Văn Thụ',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lĩnh Nam',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mai Động',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Mai',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Trì',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thịnh Liệt',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trần Phú',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tương Mai',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Hưng',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yên Sở',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đại Kim',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Định Công',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đức Giang',37);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bồ Đề',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cự Khối',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Gia Thụy',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Giang Biên',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hồng Tiến',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Biên',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngọc Lâm',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngọc Thụy',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phúc Lợi',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phúc Đồng',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sài Đồng',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạch Bàn',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thượng Thanh',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Việt Hưng',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đức Giang',38);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Mỹ',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Phú',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Tiến',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bột Xuyên',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hồng Sơn',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hợp Thanh',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hợp Tiến',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hùng Tiến',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hương Sơn',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lê Thanh',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mỹ Thành',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phù Lưu Tế',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phúc Lâm',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phùng Xá',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thượng Lâm',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tuy Lai',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vạn Kim',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuy Xá',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đại Hưng',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đại Nghĩa',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đốc Tín',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Tâm',40);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cẩm Đình',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hát Môn',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hiệp Thuận',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Liên Hiệp',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Xuyên',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngọc Tảo',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phúc Hòa',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phụng Thượng',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phương Độ',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sen Chiểu',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tam Hiệp',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tam Thuấn',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Đa',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thị trấn Gạch',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thọ Lộc',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thượng Cốc',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tích Giang',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trạch Mỹ Lộc',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vân Hà',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vân Nam',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vân Phúc',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Võng Xuyên',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Phú',42);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cấn Hữu',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cộng Hoà',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hoà Thạch',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Liệp Tuyết',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nghĩa Hương',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngọc Liệp',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngọc Mỹ',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Cát',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Mãn',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phượng Cách',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sài Sơn',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Hoà',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Phú',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạch Thán',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tuyết Nghĩa',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yên Sơn',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đại Thành',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Quang',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Xuân',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Yên',43);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bắc Phú',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bắc Sơn',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hiền Ninh',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hồng Kỳ',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim Lũ',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mai Đình',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Minh Phú',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Minh Trí',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nam Sơn',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Cường',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phù Linh',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phù Lỗ',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Minh',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quang Tiến',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Dân',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Hưng',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Minh',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Xuân',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tiên Dược',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Giã',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Việt Long',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Giang',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Thu',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Xuân',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đức Hoà',44);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cổ Đông',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim Sơn',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lê Lợi',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngô Quyền',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Thịnh',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quang Trung',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Bua',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Dung',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Lập',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Liên',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Lộc',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Long',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Màu',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Mùa',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Tân',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Tinh',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Đông',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Mỹ',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Hưng',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Sơn Trầm',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Viên Sơn',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Khanh',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Sơn',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đường Lâm',45);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bưởi',46);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nhật Tân',46);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Thượng',46);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quảng An',46);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thụy Khuê',46);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tứ Liên',46);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân La',46);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yên Phụ',46);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình Phú',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình Yên',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cẩm Yên',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cần Kiệm',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Canh Nậu',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Chàng Sơn',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Dị Nậu',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hạ Bằng',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hương Ngải',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hữu Bằng',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim Quan',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lại Thượng',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Kim',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phùng Xá',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Xã',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạch Hòa',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạch Xá',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tiến Xuân',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yên Bình',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yên Trung',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đại Đồng',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Trúc',47);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bích Hòa',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Biên Giang',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình Minh',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cao Dương',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cao Viên',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cự Khê',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Dân Hòa',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hồng Dương',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim An',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim Thư',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Liên Châu',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mỹ Hưng',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phương Trung',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tam Hưng',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Ước',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Cao',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Mai',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Thùy',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Văn',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thị trấn Kim Bài',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Dương',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đỗ Động',48);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Biên Giang',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Châu Hưng',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Dương Nội',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Duyên Hà',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hà Cầu',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hữu Hòa',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kiến Hưng',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('La Khê',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lâm Kiết',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lâm Tân',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Liên Ninh',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mỗ Lao',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngọc Hồi',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ngũ Hiệp',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nguyễn Du',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nguyễn Trãi',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú La',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Lãm',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Lộc',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Lương',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phúc La',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tả Thanh Oai',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tam Hiệp',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Triều',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Liệt',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Tân',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Trị',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tứ Hiệp',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tuân Tức',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vạn Phúc',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vạn Phúc',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Văn Quán',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Văn Điển',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Lợi',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Quỳnh',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Thành',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yên Mỹ',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yên Nghĩa',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Yết Kiêu',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đại Áng',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Mai',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Mỹ',49);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hạ Đình',50);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Khương Mai',50);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Khương Trung',50);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Khương Đình',50);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim Giang',50);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nhân Chính',50);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phương Liệt',50);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Xuân Bắc',50);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Xuân Nam',50);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Xuân Trung',50);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thượng Đình',50);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Chương Dương',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Dũng Tiến',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Duyên Thái',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hà Hồi',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hiền Giang',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Bình',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hồng Vân',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Khánh Hà',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lê Lợi',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Liên Phương',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Minh Cường',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nghiêm Xuyên',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nguyễn Trãi',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nhị Khê',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ninh Sở',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quất Động',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Minh',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thắng Lợi',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thống Nhất',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thư Phú',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tiền Phong',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tô Hiệu',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tự Nhiên',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Văn Bình',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Văn Phú',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vân Tảo',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Văn Tự',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vạn Điểm',51);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cầu Diễn',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cổ Nhuế',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Liên Mạc',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mễ Trì',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Minh Khai',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mỹ Đình',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nguyễn Trung Trực',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Diễn',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phúc Xá',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quán Thánh',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tây Mỗ',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tây Tựu',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thành Công',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thượng Cát',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thụy Phương',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trúc Bạch',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Văn',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Phương',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Đỉnh',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đại Mỗ',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Ngạc',52);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cao Thành',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Lâm',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Nam',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Phú',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hoa Sơn',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Xá',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hồng Quang',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Kim Đường',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Liên Bạt',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lưu Hoàng',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Minh Đức',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phù Lưu',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phương Tú',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Quảng Phú Cầu',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Công',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tảo Dương Văn',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thị trấn Vân Đình',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trầm Lộng',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Tú',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trường Thịnh',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vạn Thái',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Viên An',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Viên Nội',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đại Cường',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đại Hùng',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đội Bình',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Lỗ',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Tân',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đồng Tiến',53);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa An',55);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Phát',55);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Thọ Tây',55);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Thọ Đông',55);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Xuân',55);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Khuê Trung',55);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình Hiên',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình Thuận',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hải Châu 1',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hải Châu 2',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Cường',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Cường Bắc',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Cường Nam',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Thuận Tây',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Thuận Đông',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Khuê Trung',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nam Dương',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phước Ninh',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạch Thang',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Bình',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thuận Phước',57);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Bắc',58);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Châu',58);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Khương',58);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Liên',58);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Nhơn',58);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Ninh',58);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Phong',58);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Phú',58);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Phước',58);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Sơn',58);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Tiến',58);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Hiệp',59);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Khánh',59);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Minh',59);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bắc Mỹ An',60);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Hải',60);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Quý',60);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Khuê Mỹ',60);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Hải Bắc',61);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Hải Tây',61);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Hải Đông',61);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mân Thái',61);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nại Hiên Đông',61);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phước Mỹ',61);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thọ Quang',61);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Khê',62);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Chính Gián',62);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tam Thuận',62);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Chính',62);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạc Gián',62);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Lộc Đán',62);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Trung',62);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Hà',62);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Thới',63);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Hòa',63);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Tuyền',63);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thới An Đông',63);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trà Nóc',63);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Ba Láng',64);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hưng Phú',64);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hưng Thạnh',64);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lê Bình',64);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Thứ',64);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Phú',64);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thường Thạnh',64);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh An',66);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Lộc',66);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Lợi',66);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Mỹ',66);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Quới',66);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Thắng',66);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Tiến',66);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Bình',66);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Trinh',66);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Bình',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Cư',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Hòa',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Hội',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Khánh',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Lạc',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Nghiệp',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Phú',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cái Khế',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hưng Lợi',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân An',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thới Bình',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Khánh',67);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Châu Văn Liêm',68);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Hưng',68);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phước Thới',68);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thới An',68);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thới Hòa',68);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thới Long',68);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trường Lạc',68);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phong An',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phong Bình',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phong Chương',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phong Hải',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phong Hiền',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phong Hoà',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phong Mỹ',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phong Sơn',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phong Thu',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phong Xuân',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Thạnh',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thới Tân',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thới Thạnh',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trường Thắng',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trường Thành',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trường Xuân',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trường Xuân A',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trường Xuân B',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Xuân Thắng',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Điền Hải',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Điền Hoà',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Điền Hương',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Điền Lộc',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Điền Môn',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Định Môn',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Bình',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Thuận',69);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cam An Bắc',70);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cam An Nam',70);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cam Hải Tây',70);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cam Hải Đông',70);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cam Hiệp Bắc',70);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cam Hiệp Nam',70);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cam Hòa',70);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cam Phước Tây',70);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cam Tân',70);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cam Thành Bắc',70);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cam Đức',70);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Sơn Tân',70);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Hưng',71);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Lộc',71);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Hòa',71);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thới Thuận',71);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thuận An',71);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thuận Hưng',71);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Kiên',71);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trung Nhứt',71);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Anh Dũng',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hải Thành',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Nghĩa',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hưng Đạo',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Thành',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Hảo',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Hiệp',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Hòa',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Kim',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Quang',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Sơn',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Thịnh',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Thuận',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đa Phúc',72);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Tây',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Điền',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cây Trường',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Chánh Phú Hòa',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Lợi',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hưng Hòa',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lai Hưng',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lai Uyên',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Nguyên',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Mỹ Phước',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú An',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Hưng',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Định',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thới Hòa',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Trừ Văn Thố',73);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Lập',74);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Hòa',74);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Long Tân',74);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Minh Hòa',74);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Minh Tân',74);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Minh Thạnh',74);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh An',74);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thanh Tuyền',74);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Định An',74);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đinh Hiệp',74);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Định Thành',74);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Bình',75);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình An',75);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình Thắng',75);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Bình',75);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Đông Hiệp',75);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Hoà',75);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Bình',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Linh',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Long',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('An Thái',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Cát Bi',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Nam Hải',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phước Hòa',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phước Sang',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phước Vĩnh',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tam Lập',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Hiệp',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Long',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thành Tô',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tràng Cát',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Hòa',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đằng Hải',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đằng Lâm',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Hải 1',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đông Hải 2',77);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Bình Mỹ',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hiếu Liêm',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hội nghĩa',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Khánh Bình',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Lạc An',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Chánh',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Bình',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Mỹ',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Phước Khánh',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Thành',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Vĩnh Hiệp',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tân Định',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thái Hòa',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Hội',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thạnh Phước',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Thường Tân',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Uyên Hưng',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Vĩnh Tân',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Đất Cuốc',78);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Chánh Mỹ',79);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Chánh Nghĩa',79);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hiệp An',79);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hiệp Thành',79);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Hòa Phú',79);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Cường',79);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Hòa',79);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Lợi',79);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Mỹ',79);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Tân',79);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Phú Thọ',79);
INSERT INTO `Phuong_xa` (`ten_phuong_xa`,`ma_quan_huyen`) VALUES ('Tương Bình Hiệp',79);
